-- MySQL Script generated by MySQL Workbench
-- Чт. 05 нояб. 2015 14:30:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema smiu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema smiu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smiu` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `smiu` ;

-- -----------------------------------------------------
-- Table `smiu`.`device_blank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smiu`.`device_blank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_type` VARCHAR(45) NOT NULL,
  `protocol_type` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `deviceType_UNIQUE` (`device_type` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smiu`.`tag_blank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smiu`.`tag_blank` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tag_descr` VARCHAR(45) NULL,
  `tag_name` VARCHAR(100) NOT NULL,
  `tag_id` VARCHAR(45) NOT NULL,
  `delay` INT NOT NULL,
  `device_blank_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTagBlank_UNIQUE` (`id` ASC),
  INDEX `fk_tag_blank_device_blank1_idx` (`device_blank_id` ASC),
  CONSTRAINT `fk_tag_blank_device_blank1`
    FOREIGN KEY (`device_blank_id`)
    REFERENCES `smiu`.`device_blank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smiu`.`protocol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smiu`.`protocol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `protocol_settings` TEXT(500) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smiu`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smiu`.`device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `device_settings` TEXT(500) NOT NULL,
  `device_blank_id` INT NOT NULL,
  `protocol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idDevice_UNIQUE` (`id` ASC),
  INDEX `fk_device_device_blank1_idx` (`device_blank_id` ASC),
  INDEX `fk_device_protocol1_idx` (`protocol_id` ASC),
  CONSTRAINT `fk_device_device_blank1`
    FOREIGN KEY (`device_blank_id`)
    REFERENCES `smiu`.`device_blank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_device_protocol1`
    FOREIGN KEY (`protocol_id`)
    REFERENCES `smiu`.`protocol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smiu`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `smiu`.`tag` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NULL,
  `tag_time` DATE NULL,
  `tag_blank_id` INT NOT NULL,
  `device_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idTag_UNIQUE` (`id` ASC),
  INDEX `fk_tag_tag_blank1_idx` (`tag_blank_id` ASC),
  INDEX `fk_tag_device1_idx` (`device_id` ASC),
  CONSTRAINT `fk_tag_tag_blank1`
    FOREIGN KEY (`tag_blank_id`)
    REFERENCES `smiu`.`tag_blank` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_device1`
    FOREIGN KEY (`device_id`)
    REFERENCES `smiu`.`device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
